# Site settings
title:       Hannan's fascinations
email:       ali.abdulhannan@gmail.com
author:      Hannan Ali
description: "Blog where Hannan shares his thoughts about things he find fascinating. "
baseurl:     ""
url:         "https://fascinations.hannanali.tech"
date_format: "%b %-d, %Y"

# Google services
google_verification: AxhZ9PEqDwclQ827jKqeYjZ2dDOdOU6NabKYmIcicvU
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics: UA-78074618-6
google_tag_manager:
# Bing services
bing_verification:

# Optional features
animated:             false
show_related_posts:   false
show_post_footers:    false
show_social_icons:    true
ajaxify_contact_form: true
enable_mathjax: false
extended_fonts: false
enable_anchorjs: false
enable_lightbox: true

# Facebook Page integration
# (for instant articles and other stuff)
fb_page: false
fb_page_id: 

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: 

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments: true
facebook_appid: 239215849863182
facebook_comments_number: 10

github:
  repo_url: https://github.com/abdulhannanali/fascinations-of-hannan
  branch: master
  edit_doc: true ## Shows the Edit on Github text for the Post.html template, repo_url and branch are required for this

# Social icons
github_username: abdulhannanali
bitbucket_username:
stackoverflow_id:
twitter_username: computistic
skype_username:
steam_nickname:
google_plus_id:
linkedin_username: hannanali
angellist_username:
medium_id: computistic
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: false
share_linkedin: true
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: true

text:
  pagination:
    newer: 'New stuff'
    older: 'Old stuff'
  share_buttons:
    text:         'Spread the word!'
    facebook:     'Spread on Facebook'
    twitter:      'Spread on Twitter'
    googleplus:   'Spread on Google+'
    linkedin:     'Spread on LinkedIn'
    digg:         'Spread on Digg'
    tumblr:       'Spread on Tumblr'
    reddit:       'Spread on Reddit'
    stumbleupon:  'Spread on StumbleUpon'
    hackernews:   'Spread on Hacker News'
  post:
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'Related Posts'
  index:
    coming_soon: 'Coming soon...'
  contact:
    email:    'Email Address'
    content:  'What would you like to say?'
    subject:  'New submission!'
    submit:   'Say Hello'
    ajax:
      sending:  'sending..'
      sent:     'Message sent!'
      error:    'Error!'
  thanks: 'Thanks for contacting us. We will reply as soon as possible.'
  og_locale: 'en_US'

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  style: compressed
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
  - jekyll-admin
  - octopress-minify-html
# https://github.com/jekyll/jekyll/issues/2938
exclude: [vendor, node_modules]